version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL}
      - REACT_APP_SUPABASE_ANON_KEY=${REACT_APP_SUPABASE_ANON_KEY}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - supabase

  supabase:
    image: supabase/postgres:14.1.0.95
    ports:
      - "54322:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - supabase-data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d

  supabase-studio:
    image: supabase/studio:latest
    ports:
      - "3001:3000"
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DEFAULT_ORGANIZATION: Training Hub
      DEFAULT_PROJECT: Default Project

  meta:
    image: supabase/postgres-meta:v0.58.2
    depends_on:
      - supabase
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: supabase
      PG_META_DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "8080:8080"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web interface

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: supabase
      ADMINER_DESIGN: nette
    depends_on:
      - supabase

volumes:
  supabase-data:

networks:
  default:
    name: training-hub-network
